### ISSUE TITLE
Get latest build

### ISSUE THREAD

**Issue by jewome62** [Brentdynamics/LOTM-ForceGameMode#1]
Hello,

thanks for your work.
i would know how have the latest build.
Because i need param **ForceOn** in the code source.

But in bukkit plugin site, there are just stable or alpha.

can you share the jar for current code version ?

Thanks a lot

**Comment by jewome62** [comment]
Or it's possible to let some information for compile project ?

**Comment by MrBWH** [comment]
I will try over the weekend to bring the code up to 1.13.2

**Comment by jewome62** [comment]
Do you have news about this ?
Thanks
